%YAML 1.1
---
# Repo paths
epel_baseurl: http://download.fedoraproject.org/pub/epel/$releasever/$basearch/
epel_gpgurl:  https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
kubernetes_baseurl: 'https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64'
kubernetes_gpgurl: 'https://packages.cloud.google.com/yum/doc/yum-key.gpg'

# Generic rocknsm variables
rocknsm_baseurl: https://packagecloud.io/rocknsm/2/el/7/$basearch
rocknsm_gpgurl: https://packagecloud.io/rocknsm/2/gpgkey
rocknsm_local_baseurl: file:///srv/rocknsm

#Common role variables
common_mgnt_nets: "{{ rock_mgmt_nets }}"

rocknsm_package_list:
  - java-1.8.0-openjdk-headless
  - jq
  - GeoIP
  - GeoIP-update
  - tcpreplay
  - tcpdump
  - bats
  - policycoreutils-python
  - htop
  - vim
  - git
  - tmux
  - nmap-ncat
  - logrotate
  - perl-LWP-Protocol-https
  - perl-Sys-Syslog
  - perl-Crypt-SSLeay
  - perl-Archive-Tar
  - easy-rsa
