---

- hosts: servers
  roles:
    - common

    # Containerized_install: if true, all services are docker containers. Otherwise, services installed bare metal
    - { role: docker }
    - { role: elasticsearch, when: included_components.elasticsearch.enabled }
    - { role: logstash, when: included_components.logstash.enabled }


  children:
    # Primary servers are used as the main hub of the system.
    # All roles get installed onto the primary.
    primary:
      # Additional roles only installed onto primary servers.
      roles:
      - { role: kibana, when: included_components.kibana.enabled }
      #- { role: lighttpd, when: included_components['lighttpd'].enabled } #disabled for now, haproxy looks like a great replacement
      - { role: haproxy, when: included_components.haproxy.enabled }
      - { role: portainer, when: included_components.portainer.enabled }

      # Harbor must run last so that it uploads all containers installed on the machine.
      - { role: harbor, when: included_components.harbor.enabled }

      # Secondray servers are used as additional resources for the Elasticstack.
      # Common secondrary server roles are Elasticsearch, logstash, etc.
    secondary:
